[package]
name = "raspberry-monitor"
version = "0.1.0"
authors = ["Rodrigo Midea <rodrigomidea@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
vcgencmd = "0.3.1"
chrono = "0.4.11"
csv = "1.1"
